services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      VIEW_DISTANCE: "15" #дистанция в майне по умолчанию, можно уменьшить 
      TYPE:   SPIGOT
      MEMORY: 6G #здесь можно указать на какой озу будет работать
    ports:
      - "25565:25565"
    volumes:
      - /data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}
